In [107]:
import re
import nltk
nltk.download('stopwords')
import numpy as np
from nltk.corpus import stopwords
print("Welcome to the spell checker!")
print("Please enter a text to check spelling or enter quit to exit the program.")
print("--------------------------")
sent = "True"


def related_word(miss_words):
    with open('dictionary.txt', 'r') as f:
        content = f.read().split()

def min_distance(word1, word2):
    # create blank distance matrix(dm)
    dm = np.zeros((len(word1)+1,len(word2)+1))
    #print(len(word1)+1)
    #print(distance_matrix)
    for i in range(len(word1)+1):
        dm[i][0] = i
    for j in range(len(word2)+1):
        dm[0][j] = j
    for i in range(1,len(word1)+1):
        for j in range(1,len(word2)+1):
                temp = None
                if word1[i-1]==word2[j-1]:
                    temp = 0
                else:
                    temp = 2
                dm[i][j] = min(dm[i-1][j] + 1,
                                dm[i][j-1] + 1,
                                dm[i-1][j-1] + temp)
                              
    return dm[i][j]

while(sent!="quit"):
    print("\nEnter text to be checked:",end='')
    sent = str(input()).lower()
    sent = re.sub(r'[^\w\s]','',sent)
    sent_li = sent.split()

    #stop word remove
    stop_words = set(stopwords.words('english'))
    sent_wo_stpword = []
    for i in sent_li:
        if i not in stop_words:
            sent_wo_stpword.append(i)
    #print(sent_wo_stpword)
    
    # opening the dicitonary file
    with open('dictionary.txt', 'r') as f:
        content = f.read().split()
    miss_spell =[]
    for i in sent_wo_stpword:
        if i not in content:
            miss_spell.append(i)

    # the misspelled word count
    if len(miss_spell)==0:
        print("No misspellings detected")
    else:
        print("Misspelling - Suggestion")
        ## put the algorithm here 
        #empty dicitionary
        match_dict = {}
        final_dict = {}
        for i in miss_spell:
            for j in content:
                match_dict.update({j:min_distance(i,j)})
            final_dict.update({i:min(match_dict, key=match_dict.get)})
        print(final_dict)

    if sent=="quit":
        print("\nGoodBye!")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rudraksh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Welcome to the spell checker!
Please enter a text to check spelling or enter quit to exit the program.
--------------------------

Enter text to be checked:Misspelling - Suggestion
{'spain': 'pain', 'mainly': 'mail'}

Enter text to be checked:No misspellings detected

Enter text to be checked:Misspelling - Suggestion
{'deign': 'design'}

Enter text to be checked:Misspelling - Suggestion
{'raen': 'ran', 'spain': 'pain', 'fals': 'falls', 'mainly': 'mail'}

Enter text to be checked:Misspelling - Suggestion
{'quit': 'quiet'}

GoodBye!


In [89]:
import numpy as np
def min_distance(word1, word2):
    # create blank distance matrix(dm)
    dm = np.zeros((len(word1)+1,len(word2)+1))
    #print(len(word1)+1)
    #print(distance_matrix)
    for i in range(len(word1)+1):
        dm[i][0] = i
    for j in range(len(word2)+1):
        dm[0][j] = j
    for i in range(1,len(word1)+1):
        for j in range(1,len(word2)+1):
                temp = None
                if word1[i-1]==word2[j-1]:
                    temp = 0
                else:
                    temp = 2
                dm[i][j] = min(dm[i-1][j] + 1,
                                dm[i][j-1] + 1,
                                dm[i-1][j-1] + temp)
                              
    return dm

print(min_distance("execution","intention"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  3.  4.  5.  6.  7.  8.]
 [ 2.  3.  4.  5.  4.  5.  6.  7.  8.  9.]
 [ 3.  4.  5.  6.  5.  6.  7.  8.  9. 10.]
 [ 4.  5.  6.  7.  6.  7.  8.  9. 10. 11.]
 [ 5.  6.  7.  8.  7.  8.  9. 10. 11. 12.]
 [ 6.  7.  8.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  7.  8.  9. 10. 11. 10.  9.  8.]]


In [110]:

import re
import string 
from collections import Counter

import numpy as np
"""
def process_regex(path_to_text_file):
    with open(path_to_text_file, 'r') as file:
            book = file.read()
        #print(type(book))
        #Creating a new dictionary to replace British English spellings with American English spellings(taking a few words as examples)
    new_dictionary= {"colour" : "color","neighbour" : "neighbor", "savour" : "savor" , "rumour": "rumor", "flavour" : "flavor", "honour" : "honor" , "humour": "humor" ,
            "labour" : "labor" , "favour" : "favor",
            "clamour" : "clamor","vigour":"vigor" }


    book1 = re.sub(r'('+'|'.join(new_dictionary.keys()) + r')', lambda x: new_dictionary[x.group()], book)

    # Creating  a list of titles and their replacements
    titles = {'Dr.': 'Doctor',
            'Mr.': 'Mister',
            'Ms.': 'Miss',
            'Mrs.': 'Misses'}
## try
    for key in titles.keys():
        update_book = book1.replace(key, titles[key])

        # Putting the resulting text to a new file
    with open('regex.txt', 'w') as file:
        file.write(update_book)
    
    normalize_text("regex.txt")

def normalize_text(path_to_text_file):

    # Opening  the file
    with open(path_to_text_file, 'r') as file:

        book = file.read()

    # Putting  all words in lowercase
    book = book.lower()
    book= re.sub("\d+", " ", book)

    # Removing all the punctuation
    book = book.translate(str.maketrans('', '', string.punctuation))

    #removing numerics 
    #book= re.sub(" \d+", " ", book)

    # Spliting  the text into a list of words
    new_dictionary = book.split()


    # Removing  any remaining numbers
    new_dictionary = [word for word in new_dictionary if not word.isnumeric()]

    # Removing any duplicate words
    new_dictionary = list(set(new_dictionary))

 # Sorting  the words alphabetically
    new_dictionary.sort()
    tokens=book.split()
    token_counts = Counter(tokens)
    unique_tokens = set(tokens)
    unique_tokens = sorted(unique_tokens)

    # Output the dictionary to a new file
    with open('dictionary.txt', 'w') as f:
     for token in unique_tokens:
        f.write(token + '\n') 
print(process_regex('book.txt'))

"""

#spell checker funtion
def spell_checker():
    print("Welcome to the spell checker! \n Please enter a text to check spelling or enter quit to exit the program.")

   

# Pre-defined dictionary
with open('dictionary.txt','r') as file :
 latest_dictionary=file.read().split

def min_edit_distance(word1, word2):
    m, n = len(word1), len(word2)
    dp = np.zeros((m+1, n+1), dtype=int)
    
    for i in range(m+1):
        for j in range(n+1):
            if i == 0:
                dp[i][j] = j
            elif j == 0:
                dp[i][j] = i
            elif word1[i-1] == word2[j-1]:
                dp[i][j] = dp[i-1][j-1]
            else:
                dp[i][j] = 1 + min(dp[i][j-1], dp[i-1][j], dp[i-1][j-1]+1)
    return dp[i][j]

def spell_checker():
    text = input("Enter text to be checked: ").strip().split()
    
    if text=="quit":
        return"Goodbye!"
    
    misspelled = []
    for word in text :
        if word.lower() not in latest_dictionary:
            misspelled.append(word)
    if misspelled:
            print("The following word(s) are misspelled:")
            print(*misspelled)
            print("Did you mean:")
            for word in misspelled:
                closest = min(latest_dictionary, key=lambda x: min_edit_distance(word.lower(), x))
                return closest
            choice = input("Correct the misspelled word(s)? (y/n) ")
            if choice == 'y':
                corrected_text = [closest if word.lower() in misspelled else word for word in text]
                print("Corrected text:", " ".join(corrected_text))
    else:
            print("No misspelled words found.")

    # Calling  the spell checker function

spell_checker()

The following word(s) are misspelled:
raen
Did you mean:


'ran'